import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import { HPType, characters } from "@/model"
import { GetStaticProps } from "next"

const inter = Inter({ subsets: ["latin"] })

interface props {
    data: HPType[]
}

export const getStaticProps: GetStaticProps = async () => {
    const res = await characters()

    return {
        props: {
            data: res,
        },
    }
}

export default function Home(props: props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main
                style={{
                    textAlign: "center",
                    display: "flex",
                    justifyContent: "center",
                }}
            >
                <div>
                    <section>
                        <h1>pages routerによる検証</h1>
                    </section>
                    <section
                        style={{
                            width: 175,
                        }}
                    >
                        {props.data.map((item, index) => (
                            <div key={index}>
                                <picture>
                                    <Image
                                        src={item.image}
                                        width={175}
                                        height={250}
                                        alt=""
                                    />
                                </picture>
                            </div>
                        ))}
                    </section>
                </div>
            </main>
        </>
    )
}
